"""add wallet model

Revision ID: 946808c0b5ea
Revises: a44b789e9a99
Create Date: 2025-07-19 20:56:08.522967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946808c0b5ea'
down_revision = 'a44b789e9a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('total_earned', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet')
    # ### end Alembic commands ###
